# Generated by Django 5.2.8 on 2025-11-27 01:58

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/checker/file_storage/checker_files/'), upload_to='', verbose_name='Файл для проверки.')),
                ('checking_required', models.BooleanField(default=True, verbose_name='Нуждается в проверке?')),
                ('last_checked_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время последней проверки.')),
                ('last_check_status', models.CharField(choices=[('pending', 'Checking is pending'), ('in_progress', 'Checking is in progress'), ('success', 'Checked successfully'), ('failed', 'Check was failed')], default='pending', verbose_name='Статус последней проверки.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, загрузивший файл.')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed')], verbose_name='Статус проверки.')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время проверки.')),
                ('results', models.TextField(verbose_name='Результаты проверки.')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='checker.file', verbose_name='Файл, для которого производилась проверка.')),
            ],
        ),
    ]
