# Generated by Django 5.2.8 on 2025-11-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='last_checked_at',
            field=models.DateTimeField(null=True, verbose_name='Дата и время последней проверки.'),
        ),
    ]
