# Generated by Django 5.2.8 on 2025-11-27 15:07

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_alter_file_last_checked_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check',
            options={'verbose_name': 'Check', 'verbose_name_plural': 'Checks'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/checker/file_storage/checker_files/'), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.py'])], verbose_name='Файл для проверки.'),
        ),
        migrations.AlterField(
            model_name='file',
            name='last_check_status',
            field=models.CharField(choices=[('pending', 'Checking is pending'), ('success', 'Checked successfully'), ('failed', 'Check was failed')], default='pending', verbose_name='Статус последней проверки.'),
        ),
    ]
