# Generated by Django 5.2.8 on 2025-11-28 00:06

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0003_alter_check_options_alter_file_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Письмо отправлено?'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/checker-backend/file_storage/checker_files/'), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py'])], verbose_name='Файл для проверки.'),
        ),
    ]
